### ISSUE TITLE
"@type" value in output points to bioportal URL instead of ontology's own URL

### ISSUE THREAD

**Issue by bleonar5** [cedarsuite/cedarserver#2]
When modifying a template on CEDAR, if I change the "type" to be, for instance, the Dataset type from the SCHEMA ontology, and then I "populate" the template to get my JSON-LD output, I get this as my @type value: `http://data.bioontology.org/ontologies/SCHEMA/classes/http%3A%2F%2Fschema.org%2FDataset`, when the @type value should ideally be `https://schema.org/dataset`.

Without an API key, the `http://data.bioontology.org/ontologies/SCHEMA/classes/http%3A%2F%2Fschema.org%2FDataset` link does not resolve, so the JSON-LD output object is not technically valid.

**Comment by hunternet93** [comment]
I think you have the wrong repository. "CEDAR" appears to be some sort of scientific software, while this project, "Cedar", was control software for theatrical and stage productions.
